const STROKE = 2;
const CIRCLE_RADIUS = 300;
const CIRCLE_RADIUS_PLUS_STROKE = CIRCLE_RADIUS + STROKE;
const CIRCLE_RADIUS_MINUS_STROKE = CIRCLE_RADIUS - STROKE;

const MIN_SPIN_ROUNDS = 18;
const MAX_SPIN_ROUNDS = 30;
